#!/bin/bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CPP_DIR="$PROJECT_ROOT/android/app/src/main/cpp"
SOURCE_LIST_OUT=""
MANIFEST_OUT=""

usage() {
    cat <<'EOF'
Usage:
    scripts/android/generate_staged_native_metadata.sh [--cpp-dir <dir>] [--source-list-out <file>] [--manifest-out <file>]
EOF
}

fail() {
    echo "ERROR: $*" >&2
    exit 1
}

require_dir() {
    local path="$1"
    local description="$2"

    [ -d "$path" ] || fail "Missing ${description} at ${path}"
}

replace_if_different() {
    local temp_path="$1"
    local final_path="$2"

    if [ -f "$final_path" ] && cmp -s "$temp_path" "$final_path"; then
        rm -f "$temp_path"
        return 0
    fi

    mv "$temp_path" "$final_path"
}

resolve_sha256_command() {
    if command -v sha256sum >/dev/null 2>&1; then
        SHA256_CMD=(sha256sum)
        return 0
    fi

    if command -v shasum >/dev/null 2>&1; then
        SHA256_CMD=(shasum -a 256)
        return 0
    fi

    fail "Could not find sha256sum or shasum to generate the staged native manifest."
}

list_relative_files() {
    local subdir="$1"
    local pattern="${2:-}"
    local absolute_path
    local -a find_args=("$CPP_DIR/$subdir" -type f)

    if [ -n "$pattern" ]; then
        find_args+=(-name "$pattern")
    fi

    while IFS= read -r absolute_path; do
        printf '%s\n' "${absolute_path#$CPP_DIR/}"
    done < <(find "${find_args[@]}" | LC_ALL=C sort)
}

emit_cmake_list() {
    local output_file="$1"
    local variable_name="$2"
    local subdir="$3"
    local pattern="$4"
    local relative_path=""
    local entry_count=0

    printf 'set(%s\n' "$variable_name" >> "$output_file"

    while IFS= read -r relative_path; do
        [ -n "$relative_path" ] || continue
        printf '    ${R47_STAGED_CPP_DIR}/%s\n' "$relative_path" >> "$output_file"
        entry_count=$((entry_count + 1))
    done < <(list_relative_files "$subdir" "$pattern")

    printf ')\n\n' >> "$output_file"
    [ "$entry_count" -gt 0 ] || fail "No matching sources found in ${subdir}"
}

append_manifest_entries() {
    local output_file="$1"
    local subdir="$2"
    local relative_path=""
    local digest=""

    while IFS= read -r relative_path; do
        [ -n "$relative_path" ] || continue
        digest=$("${SHA256_CMD[@]}" "$CPP_DIR/$relative_path" | awk '{print $1}')
        printf '%s  %s\n' "$digest" "$relative_path" >> "$output_file"
    done < <(list_relative_files "$subdir")
}

main() {
    local source_list_tmp=""
    local manifest_tmp=""

    while [ "$#" -gt 0 ]; do
        case "$1" in
            --cpp-dir)
                shift
                [ "$#" -gt 0 ] || fail "Missing value for --cpp-dir"
                CPP_DIR="$1"
                ;;
            --source-list-out)
                shift
                [ "$#" -gt 0 ] || fail "Missing value for --source-list-out"
                SOURCE_LIST_OUT="$1"
                ;;
            --manifest-out)
                shift
                [ "$#" -gt 0 ] || fail "Missing value for --manifest-out"
                MANIFEST_OUT="$1"
                ;;
            -h|--help)
                usage
                exit 0
                ;;
            *)
                fail "Unknown option: $1"
                ;;
        esac
        shift
    done

    SOURCE_LIST_OUT="${SOURCE_LIST_OUT:-$CPP_DIR/staged_native_sources.cmake}"
    MANIFEST_OUT="${MANIFEST_OUT:-$CPP_DIR/STAGED-SOURCE-MANIFEST.txt}"

    require_dir "$CPP_DIR/c47" "staged c47 source tree"
    require_dir "$CPP_DIR/decNumberICU" "staged decNumberICU tree"
    require_dir "$CPP_DIR/generated" "staged generated tree"
    require_dir "$CPP_DIR/gmp" "staged gmp tree"
    resolve_sha256_command

    source_list_tmp=$(mktemp)
    manifest_tmp=$(mktemp)

    printf '# Generated by scripts/android/generate_staged_native_metadata.sh.\n' > "$source_list_tmp"
    printf '# Do not edit by hand; refresh through scripts/android/stage_native_sources.sh.\n' >> "$source_list_tmp"
    printf 'if("${R47_STAGED_CPP_DIR}" STREQUAL "")\n' >> "$source_list_tmp"
    printf '    set(R47_STAGED_CPP_DIR "${CMAKE_CURRENT_SOURCE_DIR}")\n' >> "$source_list_tmp"
    printf 'endif()\n\n' >> "$source_list_tmp"
    emit_cmake_list "$source_list_tmp" R47_STAGED_C47_SOURCES c47 '*.c'
    emit_cmake_list "$source_list_tmp" R47_STAGED_GENERATED_SOURCES generated '*.c'
    emit_cmake_list "$source_list_tmp" R47_STAGED_GMP_SOURCES gmp '*.c'

    printf '# Generated by scripts/android/generate_staged_native_metadata.sh.\n' > "$manifest_tmp"
    printf '# Do not edit by hand; refresh through scripts/android/stage_native_sources.sh.\n' >> "$manifest_tmp"
    printf '# sha256  relative_path\n' >> "$manifest_tmp"
    append_manifest_entries "$manifest_tmp" c47
    append_manifest_entries "$manifest_tmp" decNumberICU
    append_manifest_entries "$manifest_tmp" generated
    append_manifest_entries "$manifest_tmp" gmp

    replace_if_different "$source_list_tmp" "$SOURCE_LIST_OUT"
    replace_if_different "$manifest_tmp" "$MANIFEST_OUT"
}

main "$@"
