#ifndef KEYPAD_FIXTURE_BRIDGE_H
#define KEYPAD_FIXTURE_BRIDGE_H

#include "c47.h"

#include <stdbool.h>
#include <stdint.h>

enum {
  R47_KEYPAD_LABEL_CAPACITY = 128,
  R47_KEYPAD_LABEL_PRIMARY = 0,
  R47_KEYPAD_LABEL_F = 1,
  R47_KEYPAD_LABEL_G = 2,
  R47_KEYPAD_LABEL_LETTER = 3,
  R47_KEYPAD_LABEL_AUX = 4,
  R47_KEYPAD_LABELS_PER_KEY = 5,
  R47_KEYPAD_KEY_COUNT = 43,
  R47_KEYPAD_SCENE_CONTRACT_VERSION = 5,
  R47_KEYPAD_META_SHIFT_F = 0,
  R47_KEYPAD_META_SHIFT_G = 1,
  R47_KEYPAD_META_CALC_MODE = 2,
  R47_KEYPAD_META_USER_MODE = 3,
  R47_KEYPAD_META_ALPHA = 4,
  R47_KEYPAD_META_SOFTMENU_ID = 5,
  R47_KEYPAD_META_SOFTMENU_FIRST_ITEM = 6,
  R47_KEYPAD_META_SOFTMENU_ITEM_COUNT = 7,
  R47_KEYPAD_META_SOFTMENU_VISIBLE_ROW = 8,
  R47_KEYPAD_META_SOFTMENU_PAGE = 9,
  R47_KEYPAD_META_SOFTMENU_PAGE_COUNT = 10,
  R47_KEYPAD_META_SOFTMENU_HAS_PREVIOUS = 11,
  R47_KEYPAD_META_SOFTMENU_HAS_NEXT = 12,
  R47_KEYPAD_META_KEY_ENABLED_OFFSET = 13,
  R47_KEYPAD_META_CONTRACT_VERSION =
      R47_KEYPAD_META_KEY_ENABLED_OFFSET + R47_KEYPAD_KEY_COUNT,
  R47_KEYPAD_META_SOFTMENU_DOTTED_ROW = R47_KEYPAD_META_CONTRACT_VERSION + 1,
  R47_KEYPAD_META_FN_PREVIEW_ACTIVE = R47_KEYPAD_META_SOFTMENU_DOTTED_ROW + 1,
  R47_KEYPAD_META_FN_PREVIEW_KEY = R47_KEYPAD_META_FN_PREVIEW_ACTIVE + 1,
  R47_KEYPAD_META_FN_PREVIEW_ROW = R47_KEYPAD_META_FN_PREVIEW_KEY + 1,
  R47_KEYPAD_META_FN_PREVIEW_STATE = R47_KEYPAD_META_FN_PREVIEW_ROW + 1,
  R47_KEYPAD_META_FN_PREVIEW_TIMEOUT_ACTIVE =
      R47_KEYPAD_META_FN_PREVIEW_STATE + 1,
  R47_KEYPAD_META_FN_PREVIEW_RELEASE_EXEC =
      R47_KEYPAD_META_FN_PREVIEW_TIMEOUT_ACTIVE + 1,
  R47_KEYPAD_META_FN_PREVIEW_NOP_OR_EXECUTED =
      R47_KEYPAD_META_FN_PREVIEW_RELEASE_EXEC + 1,
  R47_KEYPAD_META_STYLE_ROLE_OFFSET =
      R47_KEYPAD_META_FN_PREVIEW_NOP_OR_EXECUTED + 1,
  R47_KEYPAD_META_LABEL_ROLE_OFFSET =
      R47_KEYPAD_META_STYLE_ROLE_OFFSET + R47_KEYPAD_KEY_COUNT,
  R47_KEYPAD_META_LAYOUT_CLASS_OFFSET =
      R47_KEYPAD_META_LABEL_ROLE_OFFSET + R47_KEYPAD_KEY_COUNT,
  R47_KEYPAD_META_SCENE_FLAGS_OFFSET =
      R47_KEYPAD_META_LAYOUT_CLASS_OFFSET + R47_KEYPAD_KEY_COUNT,
  R47_KEYPAD_META_OVERLAY_STATE_OFFSET =
      R47_KEYPAD_META_SCENE_FLAGS_OFFSET + R47_KEYPAD_KEY_COUNT,
  R47_KEYPAD_META_SHOW_VALUE_OFFSET =
      R47_KEYPAD_META_OVERLAY_STATE_OFFSET + R47_KEYPAD_KEY_COUNT,
  R47_KEYPAD_META_LENGTH =
      R47_KEYPAD_META_SHOW_VALUE_OFFSET + R47_KEYPAD_KEY_COUNT,
};

void r47_initialize_native_bridge_state(void);
void r47_native_preinit_path(const char *path);
void r47_init_runtime(int slotId);
void r47_force_refresh(void);
void r47_send_sim_function(int funcId);
void r47_send_sim_menu(int menuId);
void r47_send_sim_key(const char *keyId, bool isFn, bool isRelease);
void r47_fill_keyboard_state(int32_t *fill);
void r47_get_keypad_meta(int32_t *fill, bool isDynamic);
void r47_get_keypad_labels(
    char labels[R47_KEYPAD_KEY_COUNT * R47_KEYPAD_LABELS_PER_KEY]
               [R47_KEYPAD_LABEL_CAPACITY],
    bool isDynamic);

#endif