R47_DEFAULT_ANDROID_APPLICATION_ID=com.example.r47
R47_DEFAULT_ANDROID_JAVA_VERSION=17
R47_DEFAULT_ANDROID_GRADLE_VERSION=9.5.0
R47_DEFAULT_ANDROID_AGP_VERSION=9.2.0
R47_DEFAULT_ANDROID_COMPILE_SDK=36
R47_DEFAULT_ANDROID_TARGET_SDK=36
R47_DEFAULT_ANDROID_MIN_SDK=24
R47_DEFAULT_ANDROID_BUILD_TOOLS_VERSION=36.0.0
R47_DEFAULT_ANDROID_NDK_VERSION=29.0.14206865
R47_DEFAULT_ANDROID_CMAKE_VERSION=3.22.1
R47_DEFAULT_ANDROID_ABI_FILTERS=arm64-v8a
R47_DEFAULT_ANDROID_VERSION_CODE=1
R47_DEFAULT_ANDROID_VERSION_NAME=0.1.0
R47_DEFAULT_ANDROID_TEST_API_LEVEL=34
R47_DEFAULT_ANDROID_TEST_ABI_FILTERS=arm64-v8a,x86_64
R47_DEFAULT_XLSXIO_URL=https://github.com/brechtsanders/xlsxio.git
R47_DEFAULT_XLSXIO_COMMIT=a9016eb2eb46dcd613a68fcfcd1002b5adf64ae9