package io.github.ppigazzini.r47zen

internal enum class PhysicalKeyboardShortcutId(val wireValue: String) {
    PERCENT("SEQ_PERCENT"),
    FACTORIAL("SEQ_FACTORIAL"),
    DOTD("SEQ_DOTD"),
    HASH("SEQ_HASH"),
    MS("SEQ_MS"),
    LASTX("SEQ_LASTX"),
    ECONST("SEQ_ECONST"),
    TO_REC("SEQ_toREC"),
    TAN("SEQ_TAN"),
    ATAN("SEQ_ATAN"),
    XTHROOT("SEQ_XTHROOT"),
    UNDO("SEQ_UNDO"),
    USER("SEQ_USER"),
    IMAG_J("SEQ_IMAG_J"),
    DISP("SEQ_DISP"),
    TEN_TO_X("SEQ_10X"),
    PI("SEQ_PI"),
    TO_I("SEQ_toI"),
    HOME("SEQ_HOME"),
    MYMENU("SEQ_MYMENU"),
    TO_POL("SEQ_toPOL"),
    IMAG_POL("SEQ_IMAG_POL"),
    ALPHA("SEQ_ALPHA"),
    SIGMAP("SEQ_SIGMAP"),
    ANGLE("SEQ_ANGLE"),
    SIN("SEQ_SIN"),
    ASIN("SEQ_ASIN"),
    RUP("SEQ_RUP"),
    PREFIX("SEQ_PREFIX"),
    GTO("SEQ_GTO"),
    EXP("SEQ_EXP"),
    COMPLEX("SEQ_COMPLEX"),
    STK("SEQ_STK"),
    EXP_E("SEQ_EXP_E"),
    COS("SEQ_COS"),
    ACOS("SEQ_ACOS"),
    LBL("SEQ_LBL"),
    PRGM("SEQ_PRGM"),
    PREF("SEQ_PREF"),
    RTN("SEQ_RTN"),
    DRG("SEQ_DRG"),
    SI_N("SEQ_SI_n"),
    SI_U("SEQ_SI_u"),
    SI_M("SEQ_SI_m"),
    SI_K("SEQ_SI_k"),
    SI_MEGA("SEQ_SI_M"),
    TGLFRT("SEQ_TGLFRT"),
    AIM("SEQ_AIM"),
    ABS("SEQ_ABS");

    override fun toString(): String = wireValue
}
